version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: arbitrage
      POSTGRES_USER: arb
      POSTGRES_PASSWORD: arb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
volumes:
  pgdata:
