version: '3.9'
services:
  redis:
    image: redis:7-alpine
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: arbitrage
      POSTGRES_USER: arb
      POSTGRES_PASSWORD: arb
    volumes:
    - pgdata:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
    - 3001:3000
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    env_file:
    - ../../apps/api/.env
    healthcheck:
      test:
      - CMD-SHELL
      - curl -fsS http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
    - redis
    - postgres
  bot:
    build:
      context: ../../apps/bot
      dockerfile: Dockerfile
    ports:
    - 8010:8010
    env_file:
    - ../../apps/bot/.env
    healthcheck:
      test:
      - CMD-SHELL
      - curl -fsS http://localhost:8010/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
    - redis
    - postgres
  frontend:
    build:
      context: ../../apps/frontend
      dockerfile: Dockerfile
    ports:
    - 6000:6000
    env_file:
    - ../../apps/frontend/.env
    healthcheck:
      test:
      - CMD-SHELL
      - wget -qO- http://localhost:3000/health >/dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
    - api
    - bot
volumes:
  pgdata: null
